#sdk: "/Users/toshinobu/.rvm/gems/ruby-1.8.7-p352@rhodes/gems/rhodes-3.3.2"
sdkversion: 3.3.2
name: jqmobilekintai
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator4.3
  provisionprofile: 
  codesignidentity: 
  entitlements: 
  BundleIdentifier: com.rhomobile.jqmobilekintai
  BundleURLScheme: jqmobilekintai
  emulatortarget: iphone
wp:
  productid: 05588e20-546d-012f-6898-58b035f51d8e
symbian:
  uid: 3901562078
android:
  version: 2.1
extensions:
  - json
  - rhodes_translator
  - another-extension
